import path from "node:path";
import glob from "fast-glob";
import { assert, describe, expect, it } from "vitest";

describe("fs", () => {
  const expected = [
    "/config.json",
    expect.stringMatching(/\/functions\/api_isr_.{6}\.func\/\.vc-config\.json/),
    expect.stringMatching(/\/functions\/api_isr_.{6}\.func\/index\.mjs/),
    expect.stringMatching(/\/functions\/api_isr_.{6}\.prerender-config\.json/),
    expect.stringMatching(/\/functions\/api_page_.{6}\.func\/\.vc-config\.json/),
    expect.stringMatching(/\/functions\/api_page_.{6}\.func\/index\.mjs/),
    expect.stringMatching(/\/functions\/name_\[name]_.{6}\.func\/\.vc-config\.json/),
    expect.stringMatching(/\/functions\/name_\[name]_.{6}\.func\/index\.mjs/),
    expect.stringMatching(/\/functions\/named_\[someId]_.{6}\.func\/\.vc-config\.json/),
    expect.stringMatching(/\/functions\/named_\[someId]_.{6}\.func\/index\.mjs/),
    expect.stringMatching(
      /\/functions\/named_\[someId]_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom-server-legacy\.node\.development\.js/,
    ),
    expect.stringMatching(
      /\/functions\/named_\[someId]_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom-server-legacy\.node\.production\.js/,
    ),
    expect.stringMatching(
      /\/functions\/named_\[someId]_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom-server\.node\.development\.js/,
    ),
    expect.stringMatching(
      /\/functions\/named_\[someId]_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom-server\.node\.production\.js/,
    ),
    expect.stringMatching(
      /\/functions\/named_\[someId]_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom\.development\.js/,
    ),
    expect.stringMatching(
      /\/functions\/named_\[someId]_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom\.production\.js/,
    ),
    expect.stringMatching(/\/functions\/named_\[someId]_.{6}\.func\/node_modules\/react-dom\/index\.js/),
    expect.stringMatching(/\/functions\/named_\[someId]_.{6}\.func\/node_modules\/react-dom\/package\.json/),
    expect.stringMatching(/\/functions\/named_\[someId]_.{6}\.func\/node_modules\/react-dom\/server\.node\.js/),
    expect.stringMatching(
      /\/functions\/named_\[someId]_.{6}\.func\/node_modules\/react\/cjs\/react-jsx-runtime\.development\.js/,
    ),
    expect.stringMatching(
      /\/functions\/named_\[someId]_.{6}\.func\/node_modules\/react\/cjs\/react-jsx-runtime\.production\.js/,
    ),
    expect.stringMatching(/\/functions\/named_\[someId]_.{6}\.func\/node_modules\/react\/cjs\/react\.development\.js/),
    expect.stringMatching(/\/functions\/named_\[someId]_.{6}\.func\/node_modules\/react\/cjs\/react\.production\.js/),
    expect.stringMatching(/\/functions\/named_\[someId]_.{6}\.func\/node_modules\/react\/index\.js/),
    expect.stringMatching(/\/functions\/named_\[someId]_.{6}\.func\/node_modules\/react\/jsx-runtime\.js/),
    expect.stringMatching(/\/functions\/named_\[someId]_.{6}\.func\/node_modules\/react\/package\.json/),
    expect.stringMatching(/\/functions\/routes_\[---catchall]_.{6}\.func\/\.vc-config\.json/),
    expect.stringMatching(/\/functions\/routes_\[---catchall]_.{6}\.func\/index\.mjs/),
    expect.stringMatching(
      /\/functions\/routes_\[---catchall]_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom-server-legacy\.node\.development\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_\[---catchall]_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom-server-legacy\.node\.production\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_\[---catchall]_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom-server\.node\.development\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_\[---catchall]_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom-server\.node\.production\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_\[---catchall]_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom\.development\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_\[---catchall]_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom\.production\.js/,
    ),
    expect.stringMatching(/\/functions\/routes_\[---catchall]_.{6}\.func\/node_modules\/react-dom\/index\.js/),
    expect.stringMatching(/\/functions\/routes_\[---catchall]_.{6}\.func\/node_modules\/react-dom\/package\.json/),
    expect.stringMatching(/\/functions\/routes_\[---catchall]_.{6}\.func\/node_modules\/react-dom\/server\.node\.js/),
    expect.stringMatching(
      /\/functions\/routes_\[---catchall]_.{6}\.func\/node_modules\/react\/cjs\/react-jsx-runtime\.development\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_\[---catchall]_.{6}\.func\/node_modules\/react\/cjs\/react-jsx-runtime\.production\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_\[---catchall]_.{6}\.func\/node_modules\/react\/cjs\/react\.development\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_\[---catchall]_.{6}\.func\/node_modules\/react\/cjs\/react\.production\.js/,
    ),
    expect.stringMatching(/\/functions\/routes_\[---catchall]_.{6}\.func\/node_modules\/react\/index\.js/),
    expect.stringMatching(/\/functions\/routes_\[---catchall]_.{6}\.func\/node_modules\/react\/jsx-runtime\.js/),
    expect.stringMatching(/\/functions\/routes_\[---catchall]_.{6}\.func\/node_modules\/react\/package\.json/),
    expect.stringMatching(/\/functions\/routes_\[---catchall]_.{6}\.prerender-config\.json/),
    expect.stringMatching(/\/functions\/routes_dynamic_.{6}\.func\/\.vc-config\.json/),
    expect.stringMatching(/\/functions\/routes_dynamic_.{6}\.func\/index\.mjs/),
    expect.stringMatching(
      /\/functions\/routes_dynamic_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom-server-legacy\.node\.development\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_dynamic_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom-server-legacy\.node\.production\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_dynamic_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom-server\.node\.development\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_dynamic_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom-server\.node\.production\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_dynamic_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom\.development\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_dynamic_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom\.production\.js/,
    ),
    expect.stringMatching(/\/functions\/routes_dynamic_.{6}\.func\/node_modules\/react-dom\/index\.js/),
    expect.stringMatching(/\/functions\/routes_dynamic_.{6}\.func\/node_modules\/react-dom\/package\.json/),
    expect.stringMatching(/\/functions\/routes_dynamic_.{6}\.func\/node_modules\/react-dom\/server\.node\.js/),
    expect.stringMatching(
      /\/functions\/routes_dynamic_.{6}\.func\/node_modules\/react\/cjs\/react-jsx-runtime\.development\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_dynamic_.{6}\.func\/node_modules\/react\/cjs\/react-jsx-runtime\.production\.js/,
    ),
    expect.stringMatching(/\/functions\/routes_dynamic_.{6}\.func\/node_modules\/react\/cjs\/react\.development\.js/),
    expect.stringMatching(/\/functions\/routes_dynamic_.{6}\.func\/node_modules\/react\/cjs\/react\.production\.js/),
    expect.stringMatching(/\/functions\/routes_dynamic_.{6}\.func\/node_modules\/react\/index\.js/),
    expect.stringMatching(/\/functions\/routes_dynamic_.{6}\.func\/node_modules\/react\/jsx-runtime\.js/),
    expect.stringMatching(/\/functions\/routes_dynamic_.{6}\.func\/node_modules\/react\/package\.json/),
    expect.stringMatching(/\/functions\/routes_edge_.{6}\.func\/\.vc-config\.json/),
    expect.stringMatching(/\/functions\/routes_edge_.{6}\.func\/index\.js/),
    expect.stringMatching(
      /\/functions\/routes_edge_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom-server-legacy\.browser\.development\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_edge_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom-server-legacy\.browser\.production\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_edge_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom-server\.edge\.development\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_edge_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom-server\.edge\.production\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_edge_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom\.development\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_edge_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom\.production\.js/,
    ),
    expect.stringMatching(/\/functions\/routes_edge_.{6}\.func\/node_modules\/react-dom\/index\.js/),
    expect.stringMatching(/\/functions\/routes_edge_.{6}\.func\/node_modules\/react-dom\/package\.json/),
    expect.stringMatching(/\/functions\/routes_edge_.{6}\.func\/node_modules\/react-dom\/server\.edge\.js/),
    expect.stringMatching(
      /\/functions\/routes_edge_.{6}\.func\/node_modules\/react\/cjs\/react-jsx-runtime\.development\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_edge_.{6}\.func\/node_modules\/react\/cjs\/react-jsx-runtime\.production\.js/,
    ),
    expect.stringMatching(/\/functions\/routes_edge_.{6}\.func\/node_modules\/react\/cjs\/react\.development\.js/),
    expect.stringMatching(/\/functions\/routes_edge_.{6}\.func\/node_modules\/react\/cjs\/react\.production\.js/),
    expect.stringMatching(/\/functions\/routes_edge_.{6}\.func\/node_modules\/react\/index\.js/),
    expect.stringMatching(/\/functions\/routes_edge_.{6}\.func\/node_modules\/react\/jsx-runtime\.js/),
    expect.stringMatching(/\/functions\/routes_edge_.{6}\.func\/node_modules\/react\/package\.json/),
    expect.stringMatching(/\/functions\/routes_index_.{6}\.func\/\.vc-config\.json/),
    expect.stringMatching(/\/functions\/routes_index_.{6}\.func\/index\.mjs/),
    expect.stringMatching(
      /\/functions\/routes_index_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom-server-legacy\.node\.development\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_index_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom-server-legacy\.node\.production\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_index_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom-server\.node\.development\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_index_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom-server\.node\.production\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_index_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom\.development\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_index_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom\.production\.js/,
    ),
    expect.stringMatching(/\/functions\/routes_index_.{6}\.func\/node_modules\/react-dom\/index\.js/),
    expect.stringMatching(/\/functions\/routes_index_.{6}\.func\/node_modules\/react-dom\/package\.json/),
    expect.stringMatching(/\/functions\/routes_index_.{6}\.func\/node_modules\/react-dom\/server\.node\.js/),
    expect.stringMatching(
      /\/functions\/routes_index_.{6}\.func\/node_modules\/react\/cjs\/react-jsx-runtime\.development\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_index_.{6}\.func\/node_modules\/react\/cjs\/react-jsx-runtime\.production\.js/,
    ),
    expect.stringMatching(/\/functions\/routes_index_.{6}\.func\/node_modules\/react\/cjs\/react\.development\.js/),
    expect.stringMatching(/\/functions\/routes_index_.{6}\.func\/node_modules\/react\/cjs\/react\.production\.js/),
    expect.stringMatching(/\/functions\/routes_index_.{6}\.func\/node_modules\/react\/index\.js/),
    expect.stringMatching(/\/functions\/routes_index_.{6}\.func\/node_modules\/react\/jsx-runtime\.js/),
    expect.stringMatching(/\/functions\/routes_index_.{6}\.func\/node_modules\/react\/package\.json/),
    expect.stringMatching(/\/functions\/routes_isr_.{6}\.func\/\.vc-config\.json/),
    expect.stringMatching(/\/functions\/routes_isr_.{6}\.func\/index\.mjs/),
    expect.stringMatching(
      /\/functions\/routes_isr_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom-server-legacy\.node\.development\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_isr_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom-server-legacy\.node\.production\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_isr_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom-server\.node\.development\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_isr_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom-server\.node\.production\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_isr_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom\.development\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_isr_.{6}\.func\/node_modules\/react-dom\/cjs\/react-dom\.production\.js/,
    ),
    expect.stringMatching(/\/functions\/routes_isr_.{6}\.func\/node_modules\/react-dom\/index\.js/),
    expect.stringMatching(/\/functions\/routes_isr_.{6}\.func\/node_modules\/react-dom\/package\.json/),
    expect.stringMatching(/\/functions\/routes_isr_.{6}\.func\/node_modules\/react-dom\/server\.node\.js/),
    expect.stringMatching(
      /\/functions\/routes_isr_.{6}\.func\/node_modules\/react\/cjs\/react-jsx-runtime\.development\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_isr_.{6}\.func\/node_modules\/react\/cjs\/react-jsx-runtime\.production\.js/,
    ),
    expect.stringMatching(/\/functions\/routes_isr_.{6}\.func\/node_modules\/react\/cjs\/react\.development\.js/),
    expect.stringMatching(/\/functions\/routes_isr_.{6}\.func\/node_modules\/react\/cjs\/react\.production\.js/),
    expect.stringMatching(/\/functions\/routes_isr_.{6}\.func\/node_modules\/react\/index\.js/),
    expect.stringMatching(/\/functions\/routes_isr_.{6}\.func\/node_modules\/react\/jsx-runtime\.js/),
    expect.stringMatching(/\/functions\/routes_isr_.{6}\.func\/node_modules\/react\/package\.json/),
    expect.stringMatching(/\/functions\/routes_isr_.{6}\.prerender-config\.json/),
    expect.stringMatching(/\/functions\/routes_og-edge_.{6}\.func\/\.vc-config\.json/),
    expect.stringMatching(/\/functions\/routes_og-edge_.{6}\.func\/index\.js/),
    expect.stringMatching(/\/functions\/routes_og-edge_.{6}\.func\/node_modules\/@vercel\/og\/dist\/index\.edge\.js/),
    expect.stringMatching(
      /\/functions\/routes_og-edge_.{6}\.func\/node_modules\/@vercel\/og\/dist\/noto-sans-v27-latin-regular\.ttf/,
    ),
    expect.stringMatching(/\/functions\/routes_og-edge_.{6}\.func\/node_modules\/@vercel\/og\/dist\/resvg\.wasm/),
    expect.stringMatching(/\/functions\/routes_og-edge_.{6}\.func\/node_modules\/@vercel\/og\/dist\/yoga\.wasm/),
    expect.stringMatching(/\/functions\/routes_og-edge_.{6}\.func\/node_modules\/@vercel\/og\/package\.json/),
    expect.stringMatching(
      /\/functions\/routes_og-edge_.{6}\.func\/node_modules\/react\/cjs\/react-jsx-runtime\.development\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_og-edge_.{6}\.func\/node_modules\/react\/cjs\/react-jsx-runtime\.production\.js/,
    ),
    expect.stringMatching(/\/functions\/routes_og-edge_.{6}\.func\/node_modules\/react\/cjs\/react\.development\.js/),
    expect.stringMatching(/\/functions\/routes_og-edge_.{6}\.func\/node_modules\/react\/cjs\/react\.production\.js/),
    expect.stringMatching(/\/functions\/routes_og-edge_.{6}\.func\/node_modules\/react\/index\.js/),
    expect.stringMatching(/\/functions\/routes_og-edge_.{6}\.func\/node_modules\/react\/jsx-runtime\.js/),
    expect.stringMatching(/\/functions\/routes_og-edge_.{6}\.func\/node_modules\/react\/package\.json/),
    expect.stringMatching(/\/functions\/routes_og-node_.{6}\.func\/\.vc-config\.json/),
    expect.stringMatching(/\/functions\/routes_og-node_.{6}\.func\/index\.mjs/),
    expect.stringMatching(/\/functions\/routes_og-node_.{6}\.func\/node_modules\/@vercel\/og\/dist\/index\.node\.js/),
    expect.stringMatching(
      /\/functions\/routes_og-node_.{6}\.func\/node_modules\/@vercel\/og\/dist\/noto-sans-v27-latin-regular\.ttf/,
    ),
    expect.stringMatching(/\/functions\/routes_og-node_.{6}\.func\/node_modules\/@vercel\/og\/dist\/resvg\.wasm/),
    expect.stringMatching(/\/functions\/routes_og-node_.{6}\.func\/node_modules\/@vercel\/og\/dist\/yoga\.wasm/),
    expect.stringMatching(/\/functions\/routes_og-node_.{6}\.func\/node_modules\/@vercel\/og\/package\.json/),
    expect.stringMatching(
      /\/functions\/routes_og-node_.{6}\.func\/node_modules\/react\/cjs\/react-jsx-runtime\.development\.js/,
    ),
    expect.stringMatching(
      /\/functions\/routes_og-node_.{6}\.func\/node_modules\/react\/cjs\/react-jsx-runtime\.production\.js/,
    ),
    expect.stringMatching(/\/functions\/routes_og-node_.{6}\.func\/node_modules\/react\/cjs\/react\.development\.js/),
    expect.stringMatching(/\/functions\/routes_og-node_.{6}\.func\/node_modules\/react\/cjs\/react\.production\.js/),
    expect.stringMatching(/\/functions\/routes_og-node_.{6}\.func\/node_modules\/react\/index\.js/),
    expect.stringMatching(/\/functions\/routes_og-node_.{6}\.func\/node_modules\/react\/jsx-runtime\.js/),
    expect.stringMatching(/\/functions\/routes_og-node_.{6}\.func\/node_modules\/react\/package\.json/),
    "/static/vite.svg",
  ];

  it("should generate the right files", async () => {
    const dir = path.join(__dirname, "../../.vercel/output");
    const entries = await glob(`${dir}/**`, { dot: true });
    let mappedEntries = entries.map((e) => e.replace(dir, "")).filter((e) => !e.startsWith("/_ignore"));

    mappedEntries = Array.from(new Set(mappedEntries));

    expect(mappedEntries).toEqualUnordered(expected);
  });
});
