name: E2E (dev)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - run: pnpm playwright install chromium
      - name: Build
        run: pnpm run build
      - name: Test e2e dev
        run: pnpm test:e2e
        working-directory: examples/demo
        env:
          EDGE_CONFIG: ${{ secrets.EDGE_CONFIG }}
