# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - run: pnpm playwright install chromium
      - name: Build
        run: pnpm run build
      - name: Build build:simple
        run: pnpm run build:simple
      - name: Build build:hono
        run: pnpm run build:hono
      - name: Build build:hono-edge
        run: pnpm run build:hono-edge
      - name: Build build:demo
        run: pnpm run build:demo
      - name: Typecheck
        run: pnpm run typecheck
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test
      - name: Test e2e dev
        run: pnpm test:e2e
        working-directory: examples/demo
        env:
          EDGE_CONFIG: ${{ secrets.EDGE_CONFIG }}
